import { Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Poppins({
  weight: ["100", "300", "400", "500"],
  display: "swap",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dravora Smart Home",
  description: "Generated by dravora.id",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} antialiased`}>{children}</body>
    </html>
  );
}
